// In the format of { flag: [name (english), name (danish)] }
export const FLAGS = {
	'🇦🇩': ['andorra', 'andorra'],
	'🇦🇪': ['united arab emirates', 'forenede arabiske emirater'],
	'🇦🇫': ['afghanistan', 'afghanistan'],
	'🇦🇬': ['antigua & barbuda', 'antigua og barbuda'],
	'🇦🇮': ['anguilla', 'anguilla'],
	'🇦🇱': ['albania', 'albanien'],
	'🇦🇲': ['armenia', 'armenien'],
	'🇦🇴': ['angola', 'angola'],
	'🇦🇶': ['antarctica', 'antarctica'],
	'🇦🇷': ['argentina', 'argentina'],
	'🇦🇸': ['american samoa', 'american samoa'],
	'🇦🇹': ['austria', 'østrig'],
	'🇦🇺': ['australia', 'australien'],
	'🇦🇼': ['aruba', 'aruba'],
	'🇦🇽': ['åland islands', 'åland islands'],
	'🇦🇿': ['azerbaijan', 'azerbaijan'],
	'🇧🇦': ['bosnia & herzegovina', 'bosnien-herzegovina'],
	'🇧🇧': ['barbados', 'barbados'],
	'🇧🇩': ['bangladesh', 'bangladesh'],
	'🇧🇪': ['belgium', 'belgien'],
	'🇧🇫': ['burkina faso', 'burkina faso'],
	'🇧🇬': ['bulgaria', 'bulgarien'],
	'🇧🇭': ['bahrain', 'bahrain'],
	'🇧🇮': ['burundi', 'burundi'],
	'🇧🇯': ['benin', 'benin'],
	'🇧🇱': ['st. barthélemy', 'Saint-Barthélemy'],
	'🇧🇲': ['bermuda', 'bermuda'],
	'🇧🇳': ['brunei', 'brunei'],
	'🇧🇴': ['bolivia', 'bolivia'],
	'🇧🇶': ['caribbean netherlands', 'De tidligere Nederlandske Antiller'],
	'🇧🇷': ['brazil', 'brasilien'],
	'🇧🇸': ['bahamas', 'bahamas'],
	'🇧🇹': ['bhutan', 'bhutan'],
	'🇧🇻': ['bouvet island', 'Bouvetøen'],
	'🇧🇼': ['botswana', 'botswana'],
	'🇧🇾': ['belarus', 'belarus'],
	'🇧🇿': ['belize', 'belize'],
	'🇨🇦': ['canada', 'canada'],
	'🇨🇨': ['cocos (keeling) islands', 'cocos (keeling) øerne'],
	'🇨🇩': ['congo - kinshasa', 'congo - kinshasa'],
	'🇨🇫': ['central african republic', 'centralafrikanske republik'],
	'🇨🇬': ['congo - brazzaville', 'congo - brazzaville'],
	'🇨🇭': ['switzerland', 'schweiz'],
	'🇨🇮': ['côte d\'ivoire', 'côte d\'ivoire'],
	'🇨🇰': ['cook islands', 'Cook-øerne'],
	'🇨🇱': ['chile', 'chile'],
	'🇨🇲': ['cameroon', 'cameroon'],
	'🇨🇳': ['china', 'kina'],
	'🇨🇴': ['colombia', 'colombia'],
	'🇨🇵': ['clipperton island', 'Clippertonøen'],
	'🇨🇷': ['costa rica', 'costa rica'],
	'🇨🇺': ['cuba', 'cuba'],
	'🇨🇻': ['cape verde', 'cape verde'],
	'🇨🇼': ['curaçao', 'curaçao'],
	'🇨🇽': ['christmas island', 'Juleøerne'],
	'🇨🇾': ['cyprus', 'cypern'],
	'🇨🇿': ['czechia', 'tsjekkiet'],
	'🇩🇪': ['germany', 'tyskland'],
	'🇩🇬': ['diego garcia', 'diego garcia'],
	'🇩🇯': ['djibouti', 'djibouti'],
	'🇩🇰': ['denmark', 'danmark'],
	'🇩🇲': ['dominica', 'dominica'],
	'🇩🇴': ['dominican republic', 'dominikanske republik'],
	'🇩🇿': ['algeria', 'algeriet'],
	'🇪🇦': ['ceuta & melilla', 'ceuta og melilla'],
	'🇪🇨': ['ecuador', 'ecuador'],
	'🇪🇪': ['estonia', 'estland'],
	'🇪🇬': ['egypt', 'egypten'],
	'🇪🇭': ['western sahara', 'Vestsahara'],
	'🇪🇷': ['eritrea', 'eritrea'],
	'🇪🇸': ['spain', 'spanien'],
	'🇪🇹': ['ethiopia', 'ethiopien'],
	'🇪🇺': ['european union', 'europæisk union'],
	'🇫🇮': ['finland', 'finland'],
	'🇫🇯': ['fiji', 'fiji'],
	'🇫🇰': ['falkland islands', 'Falkland-øerne (Islas Malvinas)'],
	'🇫🇲': ['micronesia', 'Mikronesien'],
	'🇫🇴': ['faroe islands', 'færøerne'],
	'🇫🇷': ['france', 'frankrig'],
	'🇬🇦': ['gabon', 'gabon'],
	'🇬🇧': ['united kingdom', 'storbritannien'],
	'🇬🇩': ['grenada', 'grenada'],
	'🇬🇪': ['georgia', 'georgien'],
	'🇬🇫': ['french guiana', 'fransk guiana'],
	'🇬🇬': ['guernsey', 'guernsey'],
	'🇬🇭': ['ghana', 'ghana'],
	'🇬🇮': ['gibraltar', 'gibraltar'],
	'🇬🇱': ['greenland', 'grønland'],
	'🇬🇲': ['gambia', 'gambia'],
	'🇬🇳': ['guinea', 'guinea'],
	'🇬🇵': ['guadeloupe', 'guadeloupe'],
	'🇬🇶': ['equatorial guinea', 'Ækvatorial Guinea'],
	'🇬🇷': ['greece', 'grækenland'],
	'🇬🇸': ['south georgia & south sandwich islands', 'Det sydlige Georgia og de sydlige Sandwich-øer'],
	'🇬🇹': ['guatemala', 'guatemala'],
	'🇬🇺': ['guam', 'guam'],
	'🇬🇼': ['guinea-bissau', 'guinea-bissau'],
	'🇬🇾': ['guyana', 'guyana'],
	'🇭🇰': ['hong kong sar china', 'hongkong'],
	'🇭🇲': ['heard & mcdonald islands', 'heard & mcdonald islands'],
	'🇭🇳': ['honduras', 'honduras'],
	'🇭🇷': ['croatia', 'kroatien'],
	'🇭🇹': ['haiti', 'haiti'],
	'🇭🇺': ['hungary', 'ungarn'],
	'🇮🇨': ['canary islands', 'De Kanariske Øer'],
	'🇮🇩': ['indonesia', 'indonesien'],
	'🇮🇪': ['ireland', 'irland'],
  '🇮🇱': ['israel', 'israel'],
  '🇮🇹': ['italy', 'italien'],
  '🇯🇲': ['jamaica', 'jamaica'],
  '🇯🇵': ['japan', 'japan'],
  '🇯🇴': ['jordan', 'jordan'],
  '🇰🇿': ['kazakhstan', 'kasakhstan'],
  '🇰🇪': ['kenya', 'kenya'],
  '🇰🇮': ['kiribati', 'kiribati'],
  '🇰🇵': ['korea north', 'nordkorea'],
  '🇰🇷': ['korea south', 'sydkorea'],
  '🇽🇰': ['kosovo', 'kosovo'],
  '🇰🇼': ['kuwait', 'kuwait'],
  '🇰🇬': ['kyrgyzstan', 'kirgisistan'],
  '🇱🇦': ['laos', 'laos'],
  '🇱🇻': ['latvia', 'letland'],
  '🇱🇧': ['lebanon', 'libanon'],
  '🇱🇸': ['lesotho', 'lesotho'],
  '🇱🇷': ['liberia', 'liberia'],
  '🇱🇾': ['libya', 'libyen'],
  '🇱🇮': ['liechtenstein', 'liechtenstein'],
  '🇱🇹': ['lithuania', 'litauen'],
  '🇱🇺': ['luxembourg', 'luxembourg'],
  '🇲🇰': ['macedonia', 'makedonien'],
  '🇲🇬': ['madagascar', 'madagaskar'],
  '🇲🇼': ['malawi', 'malawi'],
  '🇲🇾': ['malaysia', 'malaysia'],
  '🇲🇻': ['maldives', 'maldiverne'],
  '🇲🇱': ['mali', 'mali'],
  '🇲🇹': ['malta', 'malta'],
  '🇲🇭': ['marshall islands', 'marshalløerne'],
  '🇲🇷': ['mauritania', 'mauretanien'],
  '🇲🇺': ['mauritius', 'mauritius'],
  '🇲🇽': ['mexico', 'mexico'],
  '🇲🇩': ['moldova', 'moldova'],
  '🇲🇨': ['monaco', 'monaco'],
  '🇲🇳': ['mongolia', 'mongoliet'],
  '🇲🇪': ['montenegro', 'montenegro'],
  '🇲🇦': ['morocco', 'marokko'],
  '🇲🇿': ['mozambique', 'mozambique'],
  '🇲🇲': ['myanmar, (burma)', 'myanmar (burma)'],
  '🇳🇦': ['namibia', 'namibia'],
  '🇳🇷': ['nauru', 'nauru'],
  '🇳🇵': ['nepal', 'nepal'],
  '🇳🇱': ['netherlands', 'holland'],
  '🇳🇿': ['new zealand', 'new zealand'],
  '🇳🇮': ['nicaragua', 'nicaragua'],
  '🇳🇪': ['niger', 'niger'],
  '🇳🇬': ['nigeria', 'nigeria'],
  '🇳🇴': ['norway', 'norge'],
  '🇴🇲': ['oman', 'oman'],
  '🇵🇰': ['pakistan', 'pakistan'],
  '🇵🇼': ['palau', 'palau'],
  '🇵🇦': ['panama', 'panama'],
  '🇵🇬': ['papua new guinea', 'papua ny guinea'],
  '🇵🇾': ['paraguay', 'paraguay'],
  '🇵🇪': ['peru', 'peru'],
  '🇵🇭': ['philippines', 'filippinerne'],
  '🇵🇱': ['poland', 'polen'],
  '🇵🇹': ['portugal', 'portugal'],
  '🇶🇦': ['qatar', 'qatar'],
  '🇷🇴': ['romania', 'rumænien'],
  '🇷🇺': ['russian federation', 'rusland'],
  '🇷🇼': ['rwanda', 'rwanda'],
  '🇰🇳': ['st kitts & nevis', 'saint kitts og nevis'],
  '🇱🇨': ['st lucia', 'saint lucia'],
  '🇻🇨': ['saint vincent & the grenadines', 'saint vincent og grenadinerne'],
  '🇼🇸': ['samoa', 'samoa'],
  '🇸🇲': ['san marino', 'san marino'],
  '🇸🇹': ['sao tome & principe', 'sao tome og principe'],
  '🇸🇦': ['saudi arabia', 'saudi-arabien'],
  '🇸🇳': ['senegal', 'senegal'],
  '🇷🇸': ['serbia', 'serbien'],
  '🇸🇨': ['seychelles', 'seychellerne'],
  '🇸🇱': ['sierra leone', 'sierra leone'],
  '🇸🇬': ['singapore', 'singapore'],
  '🇸🇰': ['slovakia', 'slovakiet'],
  '🇸🇮': ['slovenia', 'slovenien'],
  '🇸🇧': ['solomon islands', 'salomonøerne'],
	'🇸🇴': ['somalia', 'somalia'],
	 '🇿🇦': ['south africa', 'sydafrika'],
  '🇸🇸': ['south sudan', 'sydsudan'],
  '🇱🇰': ['sri lanka', 'sri lanka'],
  '🇸🇩': ['sudan', 'sudan'],
  '🇸🇷': ['suriname', 'surinam'],
  '🇸🇿': ['swaziland', 'swaziland'],
  '🇸🇪': ['sweden', 'sverige'],
  '🇸🇾': ['syria', 'syrien'],
  '🇹🇼': ['taiwan', 'taiwan'],
  '🇹🇯': ['tajikistan', 'tadsjikistan'],
  '🇹🇿': ['tanzania', 'tanzania'],
  '🇹🇭': ['thailand', 'thailand'],
  '🇹🇬': ['togo', 'togo'],
  '🇹🇴': ['tonga', 'tonga'],
  '🇹🇹': ['trinidad & tobago', 'trinidad og tobago'],
  '🇹🇳': ['tunisia', 'tunesien'],
  '🇹🇷': ['turkey', 'tyrkiet'],
  '🇹🇲': ['turkmenistan', 'turkmenistan'],
  '🇹🇻': ['tuvalu', 'tuvalu'],
  '🇺🇬': ['uganda', 'uganda'],
  '🇺🇦': ['ukraine', 'ukraine'],
  '🇺🇸': ['united states', 'usa'],
  '🇺🇾': ['uruguay', 'uruguay'],
  '🇺🇿': ['uzbekistan', 'usbekistan'],
  '🇻🇺': ['vanuatu', 'vanuatu'],
  '🇻🇦': ['vatican city', 'vatikanstaten'],
  '🇻🇪': ['venezuela', 'venezuela'],
  '🇻🇳': ['vietnam', 'vietnam'],
  '🇾🇪': ['yemen', 'yemen'],
  '🇿🇲': ['zambia', 'zambia'],
  '🇿🇼': ['zimbabwe', 'zimbabwe'],
} as const;

export type FlagName = typeof FLAGS[keyof typeof FLAGS][0] | typeof FLAGS[keyof typeof FLAGS][1];

export type Flag = keyof typeof FLAGS;
